/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  /* Ensure marketing tokens exist in Vite dev (JIT occasionally skipped nested surface.* utilities). */
  safelist: [
    /* ESI header/footer injects Tailwind utilities at runtime (brand-identity-pages). */
    "text-xs",
    "text-sm",
    "text-base",
    "text-white",
    "text-nowrap",
    "text-blue-600",
    "text-gray-900",
    "text-red-600",
    "tracking-tight",
    "border-2",
    "border-b-2",
    "border-blue-600",
    "cursor-pointer",
    "relative",
    "absolute",
    "fixed",
    "flex",
    "flex-col",
    "hidden",
    "block",
    "items-center",
    "justify-center",
    "pointer-events-none",
    "select-none",
    "font-bold",
    "rounded",
    "rounded-md",
    "rounded-lg",
    "rounded-full",
    "rounded-t-lg",
    "px-2",
    "px-3",
    "px-4",
    "py-0",
    "py-1",
    "py-2",
    "pr-4",
    "p-6",
    "mr-4",
    "mt-2",
    "mb-0.5",
    "gap-5",
    "size-6",
    "w-48",
    "inset-0",
    "top-full",
    "bottom-0",
    "left-0",
    "right-0",
    "z-40",
    "z-50",
    "ring-1",
    "ring-black",
    "ring-opacity-5",
    "shadow-lg",
    "origin-top-right",
    "bg-white",
    "bg-black/30",
    "bg-gradient-to-t",
    "bg-blue-50",
    "bg-blue-600",
    "from-[#153567]",
    "via-[#061D4B]",
    "to-blue-900",
    "transition-colors",
    "duration-200",
    "hover:bg-blue-50",
    "hover:bg-blue-600",
    "hover:bg-blue-700",
    "hover:bg-red-50",
    "hover:bg-gray-50",
    "hover:border-blue-700",
    "hover:text-white",
    "hover:text-blue-600",
    "hover:text-red-700",
    "focus:outline-none",
    "lg:hidden",
    "lg:inline",
    "[&_a]:!text-sm",
    "bg-gray-50",
    "bg-gray-100",
    "bg-blue-50",
    "bg-blue-100",
    "bg-blue-200",
    "bg-blue-900",
    "text-gray-50",
    "text-gray-500",
    "text-blue-900",
    "text-headings",
    "max-w-(--section-main)",
    "max-w-(--section-narrow)",
    "max-w-(--section-copy)",
    "max-w-(--section-lead)",
    "xl:px-20",
    "from-blue-900",
    "to-blue-800",
    "from-editorial-from",
    "to-editorial-to",
    "bg-surface-inverse",
    "bg-surface-inverse-input",
    "bg-surface-inverse-border",
    "border-surface-inverse-border",
    "text-surface-inverse-fg",
    "text-surface-inverse-fg-soft",
    "text-surface-inverse-fg/90",
    "hover:bg-surface-inverse-fg/10",
    "bg-tone-positive",
    "bg-tone-positive-muted",
    "bg-tone-positive-strong",
    "text-tone-positive-strong",
    "bg-tone-warn",
    "bg-tone-purple",
    "bg-feature-soft",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Instrument Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ["RecifeText", "ui-serif", "Georgia", "serif"],
        display: ["RecifeText", "ui-serif", "Georgia", "serif"],
        heading: ["RecifeText", "ui-serif", "Georgia", "serif"],
      },
      colors: {
        /* Legacy Bankrate names → same CSS vars as Shadcn semantics (single source of truth) */
        cream: "var(--background)",
        navy: {
          400: "var(--color-blue-800)",
          600: "var(--color-blue-800)",
          700: "var(--color-blue-900)",
          800: "var(--color-blue-900)",
        },
        brand: {
          blue: "var(--primary)",
          "blue-50": "var(--muted)",
          green: "var(--tone-positive)",
          "green-100": "var(--tone-positive-muted)",
          "green-700": "var(--tone-positive-strong)",
          yellow: "var(--tone-warn)",
          purple: "var(--tone-purple)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        /* Flat keys → same utilities as nested surface.inverse (more reliable in JIT) */
        "surface-inverse": "var(--surface-inverse)",
        "surface-inverse-fg": "var(--surface-inverse-foreground)",
        "surface-inverse-fg-soft": "var(--surface-inverse-foreground-soft)",
        "surface-inverse-border": "var(--surface-inverse-border)",
        "surface-inverse-input": "var(--surface-inverse-input)",
        tone: {
          positive: "var(--tone-positive)",
          "positive-strong": "var(--tone-positive-strong)",
          "positive-muted": "var(--tone-positive-muted)",
          warn: "var(--tone-warn)",
          purple: "var(--tone-purple)",
        },
        feature: {
          soft: "var(--feature-soft-blue)",
        },
        editorial: {
          from: "var(--gradient-editorial-from)",
          to: "var(--gradient-editorial-to)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        "button-sm": "var(--button-radius-sm)",
        "button-lg": "var(--button-radius-lg)",
        "2.5xl": "1.25rem",
        "3.5xl": "2.125rem",
      },
    },
  },
  plugins: [],
};
